### ISSUE TITLE
Backgrounding the app at the magic link input causes the app to return to the email input when foregrounded

### ISSUE THREAD

**Issue by munsonbh** [liveviewnative/narwin_chat#13]
After inputting my email, I swiped over to my mail client on my phone in order to copy the magic link phrase. On returning to the chat app, the app soft-reset to the email input. If I then re-entered my password and pasted the original magic link phrase in the resulting input, it was expired. There is currently no way to view the magic link without using a second device.

**Comment by hanna-del-rae** [comment]
Had the same bug on my iPhone. Had to grab a second device to check my email so that I could get a phrase that was still valid.
